# Generated by Django 6.0 on 2026-01-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0002_courseschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='day',
            field=models.CharField(choices=[('1', 'Saturday'), ('2', 'Sunday'), ('3', 'Monday'), ('4', 'Tuesday'), ('5', 'Wednesday'), ('6', 'Thursday'), ('7', 'Friday')], max_length=9),
        ),
    ]
