# Generated by Django 6.0 on 2026-01-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0003_alter_courseschedule_day'),
    ]

    operations = [
    ]
