# Generated by Django 6.0 on 2026-01-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0005_remove_student_student_password_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
